image: python:3.12

variables:
  PYTHON_VERSION: "3.12"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  POSTGRES_DB: "seguros_db_test"
  POSTGRES_USER: "seguros_user"
  POSTGRES_PASSWORD: "seguros_pass"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - lint
  - test
  - security
  - build

before_script:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install coverage
  - |
    for i in {1..30}; do
      if python -c "import psycopg2; psycopg2.connect(host='postgres', port=5432, user='seguros_user', password='seguros_pass', dbname='seguros_db_test')" 2>/dev/null; then
        echo "PostgreSQL is ready"
        break
      fi
      echo "Waiting for PostgreSQL... ($i/30)"
      sleep 2
    done
    if [ $i -eq 30 ]; then
      echo "PostgreSQL did not start in time"
      exit 1
    fi

lint:
  stage: lint
  script:
    - pip install flake8 black isort
    - echo "Running flake8..."
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics || true
    - echo "Checking code formatting with black..."
    - black --check --diff . || true
    - echo "Checking import sorting with isort..."
    - isort --check-only --diff . || true
  allow_failure: true

test:
  stage: test
  services:
    - postgres:15
  variables:
    DB_NAME: seguros_db_test
    DB_USER: seguros_user
    DB_PASSWORD: seguros_pass
    DB_HOST: postgres
    DB_PORT: 5432
    SECRET_KEY: "test-secret-key-for-ci"
    DEBUG: "True"
    ALLOWED_HOSTS: "localhost,127.0.0.1"
  script:
    - pip install coverage
    - python manage.py makemigrations --check --dry-run
    - python manage.py migrate
    - python manage.py collectstatic --noinput
    - python manage.py check --deploy
    - coverage run --source='.' manage.py test
    - coverage report
    - coverage xml
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - coverage.xml
    expire_in: 30 days

security:
  stage: security
  script:
    - pip install safety bandit
    - echo "Checking for known security vulnerabilities..."
    - safety check --json || true
    - echo "Running Bandit security linter..."
    - bandit -r . -f json -o bandit-report.json || true
  artifacts:
    paths:
      - bandit-report.json
    expire_in: 7 days
  allow_failure: true

build:
  stage: build
  script:
    - python manage.py makemigrations --check --dry-run
    - SECRET_KEY="test-secret-key" DEBUG="False" python manage.py collectstatic --noinput
    - SECRET_KEY="test-secret-key" DEBUG="False" python manage.py check --deploy
  only:
    - main
    - develop
    - master
