-- ==================================================================================
-- DEFINITIVE DATABASE RECREATION & POPULATION SCRIPT (V10 - TECHO DE CRISTAL)
-- ==================================================================================
-- WARNING: THIS SCRIPT WILL WIPE ALL EXISTING DATA IN THE 'public' SCHEMA.
-- It ensures the database structure matches the Django codebase EXACTLY.
-- Includes: Auth, Users, Policies (Complete), Claims (Complete + Timeline + Docs + Settlements),
--           Assets, Invoices, Reports, Audit, Notifications.
-- ==================================================================================

DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO public;

-- ==========================================
-- 0. SYSTEM TABLES (Django Essentials)
-- ==========================================

CREATE TABLE "django_content_type" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "app_label" VARCHAR(100) NOT NULL,
    "model" VARCHAR(100) NOT NULL
);
CREATE UNIQUE INDEX "django_content_type_app_label_model_uniq" ON "django_content_type" ("app_label", "model");

CREATE TABLE "django_session" (
    "session_key" VARCHAR(40) NOT NULL PRIMARY KEY,
    "session_data" TEXT NOT NULL,
    "expire_date" TIMESTAMPTZ NOT NULL
);
CREATE INDEX "django_session_expire_date_idx" ON "django_session" ("expire_date");

CREATE TABLE "django_migrations" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "app" VARCHAR(255) NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "applied" TIMESTAMPTZ NOT NULL
);

-- ==========================================
-- 0.1 AUTH TABLES
-- ==========================================

CREATE TABLE "auth_group" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE "auth_permission" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "content_type_id" INTEGER NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED,
    "codename" VARCHAR(100) NOT NULL
);
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_uniq" ON "auth_permission" ("content_type_id", "codename");

CREATE TABLE "auth_group_permissions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "group_id" INTEGER NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED,
    "permission_id" INTEGER NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_uniq" ON "auth_group_permissions" ("group_id", "permission_id");


-- ==========================================
-- 1. BUSINESS TABLES (Matches Django Models)
-- ==========================================

-- 1.1 USERS (accounts_userprofile)
CREATE TABLE "accounts_userprofile" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "password" VARCHAR(128) NOT NULL,
    "last_login" TIMESTAMPTZ,
    "is_superuser" BOOLEAN NOT NULL,
    "username" VARCHAR(150) NOT NULL UNIQUE,
    "first_name" VARCHAR(150) NOT NULL,
    "last_name" VARCHAR(150) NOT NULL,
    "email" VARCHAR(254) NOT NULL,
    "is_staff" BOOLEAN NOT NULL,
    "is_active" BOOLEAN NOT NULL,
    "date_joined" TIMESTAMPTZ NOT NULL,
    "full_name" VARCHAR(255) NOT NULL,
    "role" VARCHAR(20) NOT NULL,
    "department" VARCHAR(100) NOT NULL,
    "phone" VARCHAR(20) NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL
);

-- 1.1.1 USER RELATIONS (M2M)
CREATE TABLE "accounts_userprofile_groups" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userprofile_id" BIGINT NOT NULL REFERENCES "accounts_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED,
    "group_id" INTEGER NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE UNIQUE INDEX "accounts_userprofile_groups_userprofile_id_group_id_uniq" ON "accounts_userprofile_groups" ("userprofile_id", "group_id");

CREATE TABLE "accounts_userprofile_user_permissions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userprofile_id" BIGINT NOT NULL REFERENCES "accounts_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED,
    "permission_id" INTEGER NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE UNIQUE INDEX "accounts_userprofile_user_permissions_userprofile_id_permission_id_uniq" ON "accounts_userprofile_user_permissions" ("userprofile_id", "permission_id");


-- 1.2 COMPANIES
CREATE TABLE "companies_insurancecompany" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "ruc" VARCHAR(13) NOT NULL,
    "address" TEXT NOT NULL,
    "phone" VARCHAR(20) NOT NULL,
    "email" VARCHAR(254) NOT NULL,
    "contact_person" VARCHAR(255) NOT NULL,
    "is_active" BOOLEAN NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL
);

-- 1.3 BROKERS
CREATE TABLE "brokers_broker" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "ruc" VARCHAR(13) NOT NULL,
    "address" TEXT NOT NULL,
    "phone" VARCHAR(20) NOT NULL,
    "email" VARCHAR(254) NOT NULL,
    "contact_person" VARCHAR(255) NOT NULL,
    "commission_percentage" NUMERIC(5, 2) NOT NULL,
    "is_active" BOOLEAN NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL
);

-- 1.4 POLICIES (UPDATED WITH ALL FIELDS)
CREATE TABLE "policies_policy" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "policy_number" VARCHAR(50) NOT NULL UNIQUE,
    "group_type" VARCHAR(20) NOT NULL,
    "subgroup" VARCHAR(100) NOT NULL,
    "branch" VARCHAR(100) NOT NULL,
    "start_date" DATE NOT NULL,
    "end_date" DATE NOT NULL,
    "issue_date" DATE,
    "fecha_renovacion" DATE,
    "alerta_vencimiento_dias" INTEGER NOT NULL DEFAULT 30,
    "objeto_asegurado" VARCHAR(255) NOT NULL,
    "prima" NUMERIC(15, 2) NOT NULL,
    "costo_servicio" NUMERIC(15, 2) NOT NULL DEFAULT 0,
    "insured_value" NUMERIC(15, 2) NOT NULL,
    "contrib_superintendencia" NUMERIC(15, 2) NOT NULL DEFAULT 0,
    "contrib_seguro_campesino" NUMERIC(15, 2) NOT NULL DEFAULT 0,
    "derecho_emision" NUMERIC(15, 2) NOT NULL DEFAULT 0,
    "base_imponible" NUMERIC(15, 2) NOT NULL DEFAULT 0,
    "iva" NUMERIC(15, 2) NOT NULL DEFAULT 0,
    "total_facturado" NUMERIC(15, 2) NOT NULL DEFAULT 0,
    "retencion" NUMERIC(15, 2) NOT NULL DEFAULT 0,
    "modalidad_facturacion" VARCHAR(20) NOT NULL DEFAULT 'anual',
    "coverage_description" TEXT NOT NULL,
    "observations" TEXT NOT NULL,
    "status" VARCHAR(20) NOT NULL DEFAULT 'active',
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "broker_id" BIGINT REFERENCES "brokers_broker" ("id") DEFERRABLE INITIALLY DEFERRED,
    "insurance_company_id" BIGINT NOT NULL REFERENCES "companies_insurancecompany" ("id") DEFERRABLE INITIALLY DEFERRED,
    "responsible_user_id" BIGINT REFERENCES "accounts_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED
);

-- 1.5 ASSETS
CREATE TABLE "assets_asset" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "asset_code" VARCHAR(50) NOT NULL UNIQUE,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT NOT NULL,
    "brand" VARCHAR(100) NOT NULL,
    "model" VARCHAR(100) NOT NULL,
    "serial_number" VARCHAR(100) NOT NULL,
    "asset_type" VARCHAR(20) NOT NULL,
    "location" VARCHAR(255) NOT NULL,
    "acquisition_date" DATE NOT NULL,
    "acquisition_cost" NUMERIC(15, 2) NOT NULL,
    "current_value" NUMERIC(15, 2) NOT NULL,
    "condition_status" VARCHAR(20) NOT NULL DEFAULT 'bueno',
    "is_insured" BOOLEAN NOT NULL DEFAULT FALSE,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "custodian_id" BIGINT NOT NULL REFERENCES "accounts_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED,
    "insurance_policy_id" BIGINT REFERENCES "policies_policy" ("id") DEFERRABLE INITIALLY DEFERRED,
    "responsible_user_id" BIGINT NOT NULL REFERENCES "accounts_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED
);

-- 1.6 CLAIMS (UPDATED WITH ALL FIELDS)
CREATE TABLE "claims_claim" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "claim_number" VARCHAR(50) NOT NULL UNIQUE,
    "fecha_siniestro" DATE NOT NULL,
    "incident_date" DATE NOT NULL,
    "fecha_notificacion" DATE NOT NULL,
    "report_date" DATE NOT NULL,
    "fecha_cierre" DATE,
    "causa" TEXT NOT NULL,
    "ubicacion_detallada" TEXT NOT NULL,
    "incident_location" VARCHAR(255) NOT NULL,
    "incident_description" TEXT NOT NULL,
    "status" VARCHAR(25) NOT NULL DEFAULT 'pendiente',
    
    -- Cached Asset Info
    "asset_type" VARCHAR(100) NOT NULL,
    "asset_description" VARCHAR(255) NOT NULL,
    "asset_code" VARCHAR(50) NOT NULL DEFAULT '',

    -- Financials
    "estimated_loss" NUMERIC(15, 2) NOT NULL,
    "approved_amount" NUMERIC(15, 2),
    "payment_date" DATE,

    -- SLAs
    "fecha_solicitud_documentos" DATE,
    "fecha_docs_completos" DATE,
    "fecha_envio_aseguradora" DATE,
    "fecha_respuesta_aseguradora" DATE,
    "dias_limite_documentos" INTEGER NOT NULL DEFAULT 30,
    "dias_limite_respuesta_aseguradora" INTEGER NOT NULL DEFAULT 8,

    -- Validation & Notifications
    "validation_comments" TEXT NOT NULL DEFAULT '',
    "validation_date" TIMESTAMPTZ,
    "validated_by_id" BIGINT REFERENCES "accounts_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED,
    "broker_notificado_id" BIGINT REFERENCES "brokers_broker" ("id") DEFERRABLE INITIALLY DEFERRED,
    "aseguradora_notificada_id" BIGINT REFERENCES "companies_insurancecompany" ("id") DEFERRABLE INITIALLY DEFERRED,

    -- Relations
    "asset_id" BIGINT REFERENCES "assets_asset" ("id") DEFERRABLE INITIALLY DEFERRED,
    "policy_id" BIGINT REFERENCES "policies_policy" ("id") DEFERRABLE INITIALLY DEFERRED,
    "cobertura_aplicada_id" BIGINT,
    "rejection_reason" TEXT NOT NULL DEFAULT '',
    
    -- Meta
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "assigned_to_id" BIGINT REFERENCES "accounts_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED,
    "created_by_id" BIGINT REFERENCES "accounts_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED,
    "reportante_id" BIGINT REFERENCES "accounts_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED,
    "reported_by_id" BIGINT REFERENCES "accounts_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED
);

-- 1.6.1 CLAIM TIMELINES (NEW)
CREATE TABLE "claims_claimtimeline" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "event_type" VARCHAR(20) NOT NULL,
    "event_description" TEXT NOT NULL,
    "old_status" VARCHAR(25) NOT NULL DEFAULT '',
    "new_status" VARCHAR(25) NOT NULL DEFAULT '',
    "notes" TEXT NOT NULL DEFAULT '',
    "created_at" TIMESTAMPTZ NOT NULL,
    "claim_id" BIGINT NOT NULL REFERENCES "claims_claim" ("id") DEFERRABLE INITIALLY DEFERRED,
    "created_by_id" BIGINT REFERENCES "accounts_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED
);

-- 1.6.2 CLAIM DOCUMENTS (NEW)
CREATE TABLE "claims_claimdocument" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "document_name" VARCHAR(255) NOT NULL,
    "document_type" VARCHAR(20) NOT NULL,
    "version" INTEGER NOT NULL DEFAULT 1,
    "is_latest_version" BOOLEAN NOT NULL DEFAULT TRUE,
    "file" VARCHAR(100) NOT NULL, 
    "file_size" INTEGER NOT NULL,
    "mime_type" VARCHAR(100) NOT NULL,
    "description" TEXT NOT NULL,
    "tags" VARCHAR(500) NOT NULL DEFAULT '',
    "is_required" BOOLEAN NOT NULL DEFAULT FALSE,
    "required_deadline" DATE,
    "status" VARCHAR(20) NOT NULL DEFAULT 'active',
    "uploaded_at" TIMESTAMPTZ NOT NULL,
    "last_modified" TIMESTAMPTZ NOT NULL,
    "claim_id" BIGINT NOT NULL REFERENCES "claims_claim" ("id") DEFERRABLE INITIALLY DEFERRED,
    "parent_document_id" BIGINT REFERENCES "claims_claimdocument" ("id") DEFERRABLE INITIALLY DEFERRED,
    "uploaded_by_id" BIGINT NOT NULL REFERENCES "accounts_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED
);

-- 1.6.3 CLAIM SETTLEMENTS (NEW)
CREATE TABLE "claims_claimsettlement" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "settlement_number" VARCHAR(50) NOT NULL UNIQUE,
    "numero_reclamo" VARCHAR(100) NOT NULL,
    "claim_reference_number" VARCHAR(100) NOT NULL DEFAULT '',
    "valor_total_reclamo" NUMERIC(15, 2) NOT NULL,
    "total_claim_amount" NUMERIC(12, 2) NOT NULL,
    "deducible_aplicado" NUMERIC(15, 2) NOT NULL DEFAULT 0,
    "deductible_amount" NUMERIC(12, 2) NOT NULL DEFAULT 0,
    "depreciacion" NUMERIC(15, 2) NOT NULL DEFAULT 0,
    "depreciation_amount" NUMERIC(12, 2) NOT NULL DEFAULT 0,
    "valor_a_pagar" NUMERIC(15, 2) NOT NULL,
    "final_payment_amount" NUMERIC(12, 2) NOT NULL,
    "fecha_recepcion_finiquito" DATE NOT NULL,
    "settlement_date" DATE NOT NULL,
    "fecha_firma" DATE,
    "signed_date" DATE,
    "fecha_limite_pago" DATE,
    "fecha_pago" DATE,
    "payment_date" DATE,
    "payment_reference" VARCHAR(100) NOT NULL DEFAULT '',
    "notificado_gerencia_financiera" BOOLEAN NOT NULL DEFAULT FALSE,
    "fecha_notificacion_gerencia" TIMESTAMPTZ,
    "status" VARCHAR(20) NOT NULL DEFAULT 'draft',
    "settlement_document" VARCHAR(100),
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "approved_by_id" BIGINT REFERENCES "accounts_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED,
    "claim_id" BIGINT NOT NULL UNIQUE REFERENCES "claims_claim" ("id") DEFERRABLE INITIALLY DEFERRED,
    "created_by_id" BIGINT REFERENCES "accounts_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED
);

-- 1.7 INVOICES
CREATE TABLE "invoices_invoice" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "invoice_number" VARCHAR(50) NOT NULL UNIQUE,
    "invoice_date" DATE NOT NULL,
    "due_date" DATE NOT NULL,
    "payment_date" DATE,
    "fecha_vencimiento" DATE NOT NULL,
    "payment_status" VARCHAR(25) NOT NULL DEFAULT 'pendiente',
    "documento_contable" VARCHAR(100) NOT NULL DEFAULT '',
    
    -- Calculated/Monetary Fields
    "premium" NUMERIC(15, 2) NOT NULL,
    "superintendence_contribution" NUMERIC(15, 2) NOT NULL,
    "farm_insurance_contribution" NUMERIC(15, 2) NOT NULL,
    "emission_rights" NUMERIC(15, 2) NOT NULL,
    "tax_base" NUMERIC(15, 2) NOT NULL,
    "iva" NUMERIC(15, 2) NOT NULL,
    "withholding_tax" NUMERIC(15, 2) NOT NULL DEFAULT 0,
    "early_payment_discount" NUMERIC(15, 2) NOT NULL DEFAULT 0,
    "total_amount" NUMERIC(15, 2) NOT NULL,
    "descuento_pronto_pago_aplicado" BOOLEAN NOT NULL DEFAULT FALSE,
    "descuento_pronto_pago_valor" NUMERIC(15, 2) NOT NULL DEFAULT 0,
    "dias_desde_emision" INTEGER NOT NULL DEFAULT 0,
    
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "created_by_id" BIGINT NOT NULL REFERENCES "accounts_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED,
    "policy_id" BIGINT NOT NULL REFERENCES "policies_policy" ("id") DEFERRABLE INITIALLY DEFERRED
);

-- 1.8 AUDIT LOGS
CREATE TABLE "audit_auditlog" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "action_type" VARCHAR(20) NOT NULL,
    "entity_type" VARCHAR(20) NOT NULL,
    "entity_id" VARCHAR(100) NOT NULL,
    "description" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "user_id" BIGINT REFERENCES "accounts_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED,
    "content_type_id" INTEGER REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED,
    "object_id" INTEGER,
    "old_values" JSONB,
    "new_values" JSONB,
    "ip_address" INET,
    "user_agent" TEXT
);

-- 1.9 REPORTS (NEW)
CREATE TABLE "reports_report" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "report_type" VARCHAR(50) NOT NULL,
    "description" TEXT NOT NULL,
    "filters" JSONB NOT NULL DEFAULT '{}',
    "parameters" JSONB NOT NULL DEFAULT '{}',
    "is_scheduled" BOOLEAN NOT NULL DEFAULT FALSE,
    "schedule_frequency" VARCHAR(20) NOT NULL DEFAULT '',
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "last_run" TIMESTAMPTZ,
    "created_by_id" BIGINT REFERENCES "accounts_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE "reports_report_recipients" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "report_id" BIGINT NOT NULL REFERENCES "reports_report" ("id") DEFERRABLE INITIALLY DEFERRED,
    "userprofile_id" BIGINT NOT NULL REFERENCES "accounts_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE "reports_reportexecution" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "executed_at" TIMESTAMPTZ NOT NULL,
    "execution_time_seconds" DOUBLE PRECISION NOT NULL,
    "success" BOOLEAN NOT NULL DEFAULT TRUE,
    "error_message" TEXT NOT NULL,
    "export_format" VARCHAR(10) NOT NULL DEFAULT '',
    "exported_file" VARCHAR(100),
    "executed_by_id" BIGINT REFERENCES "accounts_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED,
    "report_id" BIGINT NOT NULL REFERENCES "reports_report" ("id") DEFERRABLE INITIALLY DEFERRED
);

-- 1.10 NOTIFICATIONS
CREATE TABLE "notifications_notification" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "notification_type" VARCHAR(20) NOT NULL,
    "title" VARCHAR(255) NOT NULL,
    "message" TEXT NOT NULL,
    "link" VARCHAR(200) NOT NULL,
    "is_read" BOOLEAN NOT NULL DEFAULT FALSE,
    "priority" VARCHAR(10) NOT NULL DEFAULT 'normal',
    "created_at" TIMESTAMPTZ NOT NULL,
    "user_id" BIGINT NOT NULL REFERENCES "accounts_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE "notifications_emailtemplate" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(100) NOT NULL UNIQUE,
    "template_type" VARCHAR(30) NOT NULL,
    "recipient_type" VARCHAR(20) NOT NULL,
    "subject" VARCHAR(255) NOT NULL,
    "body_html" TEXT NOT NULL,
    "body_text" TEXT NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT TRUE,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "created_by_id" BIGINT REFERENCES "accounts_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE "notifications_emaillog" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "recipient_email" VARCHAR(254) NOT NULL,
    "recipient_name" VARCHAR(255) NOT NULL,
    "subject" VARCHAR(255) NOT NULL,
    "status" VARCHAR(10) NOT NULL DEFAULT 'pending',
    "sent_at" TIMESTAMPTZ,
    "error_message" TEXT NOT NULL,
    "context_data" JSONB NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMPTZ NOT NULL,
    "template_id" BIGINT NOT NULL REFERENCES "notifications_emailtemplate" ("id") DEFERRABLE INITIALLY DEFERRED,
    "claim_id" BIGINT REFERENCES "claims_claim" ("id") DEFERRABLE INITIALLY DEFERRED,
    "policy_id" BIGINT REFERENCES "policies_policy" ("id") DEFERRABLE INITIALLY DEFERRED,
    "invoice_id" BIGINT REFERENCES "invoices_invoice" ("id") DEFERRABLE INITIALLY DEFERRED,
    "created_by_id" BIGINT REFERENCES "accounts_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE "notifications_alert" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "alert_type" VARCHAR(20) NOT NULL,
    "description" TEXT NOT NULL,
    "conditions" JSONB NOT NULL DEFAULT '{}',
    "email_recipients" TEXT NOT NULL,
    "frequency" VARCHAR(10) NOT NULL DEFAULT 'daily',
    "is_active" BOOLEAN NOT NULL DEFAULT TRUE,
    "last_run" TIMESTAMPTZ,
    "next_run" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "created_by_id" BIGINT REFERENCES "accounts_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE "notifications_alert_recipients" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "alert_id" BIGINT NOT NULL REFERENCES "notifications_alert" ("id") DEFERRABLE INITIALLY DEFERRED,
    "userprofile_id" BIGINT NOT NULL REFERENCES "accounts_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED
);

-- ==========================================
-- 2. DATA POPULATION
-- ==========================================

-- 2.1 USERS (Password: Seguros2025!)
INSERT INTO accounts_userprofile (id, password, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, full_name, role, department, phone, created_at, updated_at)
VALUES 
(1, 'pbkdf2_sha256$260000$reUseMeHashOrReset$invalidPlaceholderFixedByShell', true, 'admin', 'Admin', 'Original', 'admin@seguros.com', true, true, NOW(), 'Sys Admin', 'admin', 'IT', '0999999999', NOW(), NOW()),
(2, 'pbkdf2_sha256$260000$reUseMeHashOrReset$invalidPlaceholderFixedByShell', false, 'ajustador1', 'Juan', 'Perez', 'juan@seguros.com', true, true, NOW(), 'Juan Perez', 'insurance_manager', 'Siniestros', '0988888888', NOW(), NOW()),
(3, 'pbkdf2_sha256$260000$reUseMeHashOrReset$invalidPlaceholderFixedByShell', false, 'cliente1', 'Maria', 'Gomez', 'maria@cliente.com', false, true, NOW(), 'Maria Gomez', 'requester', 'Finanzas', '0977777777', NOW(), NOW());

-- 2.2 COMPANIES
INSERT INTO companies_insurancecompany (id, name, ruc, address, phone, email, contact_person, is_active, created_at, updated_at)
VALUES 
(1, 'Seguros Confianza', '1790000000001', 'Av. Amazonas', '022222222', 'contact@confianza.com', 'Gerente Ventas', true, NOW(), NOW()),
(2, 'Aseguradora del Sur', '1790000000002', 'Calle Larga', '042222222', 'info@delsur.com', 'Soporte', true, NOW(), NOW());

-- 2.3 POLICIES
INSERT INTO policies_policy (id, policy_number, group_type, subgroup, branch, start_date, end_date, issue_date, insured_value, prima, coverage_description, observations, status, created_at, updated_at, insurance_company_id, responsible_user_id, objeto_asegurado)
VALUES 
(1, 'POL-VH-2025-001', 'patrimoniales', 'Livianos', 'Automotores', '2025-01-01', '2025-12-31', '2025-01-01', 45000.00, 1200.00, 'Cobertura Todo Riesgo', 'Ninguna', 'active', NOW(), NOW(), 1, 1, 'Toyota Fortuner 2024'),
(2, 'POL-PR-2025-002', 'patrimoniales', 'Incendio', 'Incendio y Aliadas', '2025-03-01', '2026-02-28', '2025-03-01', 120000.00, 2500.00, 'Incendio y Terremoto', 'Sede Central', 'active', NOW(), NOW(), 2, 1, 'Departamento Centro');

-- 2.4 ASSETS
INSERT INTO assets_asset (id, asset_code, name, asset_type, description, location, acquisition_date, acquisition_cost, current_value, condition_status, is_insured, created_at, updated_at, custodian_id, responsible_user_id, insurance_policy_id, brand, model, serial_number)
VALUES 
(1, 'VEH-001', 'Toyota Fortuner 2024', 'vehiculo', 'SUV 4x4 Negro', 'Quito', '2024-01-15', 50000.00, 45000.00, 'bueno', true, NOW(), NOW(), 3, 3, 1, 'Toyota', 'Fortuner', 'SN001'),
(2, 'PROP-001', 'Departamento Centro', 'otros', 'Departamento 3 dormitorios', 'Guayaquil', '2022-05-20', 110000.00, 120000.00, 'bueno', true, NOW(), NOW(), 3, 3, 2, 'N/A', 'N/A', 'N/A');

-- 2.5 CLAIMS
INSERT INTO claims_claim (id, claim_number, fecha_siniestro, incident_date, fecha_notificacion, report_date, causa, ubicacion_detallada, incident_location, incident_description, status, estimated_loss, asset_id, policy_id, created_at, updated_at, created_by_id, asset_type, asset_description, asset_code, reportante_id, reported_by_id)
VALUES 
(1, 'CLM-2025-001', '2025-06-15', '2025-06-15', NOW(), NOW(), 'Colisión', 'Av. Shyris', 'Av. Shyris', 'Choque lateral', 'pendiente', 0.00, 1, 1, NOW(), NOW(), 3, 'vehiculo', 'Toyota Fortuner', 'VEH-001', 3, 3),
(2, 'CLM-2025-002', '2025-07-20', '2025-07-20', NOW(), NOW(), 'Daño por agua', 'Edif. Torre', 'Edif. Torre', 'Rotura tubería', 'en_revision', 0.00, 2, 2, NOW(), NOW(), 3, 'otros', 'Departamento Centro', 'PROP-001', 3, 3);

-- 2.6 INVOICES
INSERT INTO invoices_invoice (id, invoice_number, policy_id, invoice_date, due_date, fecha_vencimiento, total_amount, premium, superintendence_contribution, farm_insurance_contribution, emission_rights, tax_base, iva, payment_status, created_at, updated_at, created_by_id)
VALUES 
(1, 'FAC-001', 1, '2025-01-01', '2025-01-15', '2025-01-15', 1500.00, 1200.00, 42.00, 6.00, 0.00, 1248.00, 187.20, 'pagada', NOW(), NOW(), 1);

-- Sync Sequences
SELECT setval('accounts_userprofile_id_seq', (SELECT MAX(id) FROM accounts_userprofile));
SELECT setval('companies_insurancecompany_id_seq', (SELECT MAX(id) FROM companies_insurancecompany));
SELECT setval('policies_policy_id_seq', (SELECT MAX(id) FROM policies_policy));
SELECT setval('assets_asset_id_seq', (SELECT MAX(id) FROM assets_asset));
SELECT setval('claims_claim_id_seq', (SELECT MAX(id) FROM claims_claim));
SELECT setval('invoices_invoice_id_seq', (SELECT MAX(id) FROM invoices_invoice));
