-- Generated from SQLite schema (db.sqlite3) to PostgreSQL DDL
-- Note: review NUMERIC precision/scale and ON DELETE/UPDATE actions as needed.
BEGIN;
SET client_min_messages TO WARNING;

CREATE TABLE IF NOT EXISTS "accounts_userprofile" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "password" VARCHAR(128) NOT NULL,
  "last_login" TIMESTAMPTZ,
  "is_superuser" BOOLEAN NOT NULL,
  "username" VARCHAR(150) NOT NULL,
  "first_name" VARCHAR(150) NOT NULL,
  "last_name" VARCHAR(150) NOT NULL,
  "email" VARCHAR(254) NOT NULL,
  "is_staff" BOOLEAN NOT NULL,
  "is_active" BOOLEAN NOT NULL,
  "date_joined" TIMESTAMPTZ NOT NULL,
  "full_name" VARCHAR(255) NOT NULL,
  "role" VARCHAR(20) NOT NULL,
  "department" VARCHAR(100) NOT NULL,
  "phone" VARCHAR(20) NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "accounts_userprofile_groups" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userprofile_id" BIGINT NOT NULL,
  "group_id" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "accounts_userprofile_user_permissions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userprofile_id" BIGINT NOT NULL,
  "permission_id" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "assets_asset" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "asset_code" VARCHAR(50) NOT NULL,
  "name" VARCHAR(255) NOT NULL,
  "description" TEXT NOT NULL,
  "brand" VARCHAR(100) NOT NULL,
  "model" VARCHAR(100) NOT NULL,
  "serial_number" VARCHAR(100) NOT NULL,
  "asset_type" VARCHAR(20) NOT NULL,
  "location" VARCHAR(255) NOT NULL,
  "acquisition_date" DATE NOT NULL,
  "acquisition_cost" NUMERIC NOT NULL,
  "current_value" NUMERIC NOT NULL,
  "condition_status" VARCHAR(20) NOT NULL,
  "is_insured" BOOLEAN NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "custodian_id" BIGINT NOT NULL,
  "insurance_policy_id" BIGINT,
  "responsible_user_id" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS "audit_auditlog" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "action_type" VARCHAR(20) NOT NULL,
  "entity_type" VARCHAR(20) NOT NULL,
  "object_id" INTEGER,
  "old_values" TEXT,
  "new_values" TEXT,
  "description" TEXT NOT NULL,
  "ip_address" CHAR(39),
  "user_agent" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL,
  "content_type_id" INTEGER,
  "user_id" BIGINT,
  "entity_id" VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS "auth_group" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS "auth_group_permissions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "group_id" INTEGER NOT NULL,
  "permission_id" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "auth_permission" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content_type_id" INTEGER NOT NULL,
  "codename" VARCHAR(100) NOT NULL,
  "name" VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "brokers_broker" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "ruc" VARCHAR(13) NOT NULL,
  "address" TEXT NOT NULL,
  "phone" VARCHAR(20) NOT NULL,
  "email" VARCHAR(254) NOT NULL,
  "contact_person" VARCHAR(255) NOT NULL,
  "commission_percentage" NUMERIC NOT NULL,
  "is_active" BOOLEAN NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "claims_claim" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "claim_number" VARCHAR(50) NOT NULL,
  "incident_date" DATE NOT NULL,
  "report_date" DATE NOT NULL,
  "incident_location" VARCHAR(255) NOT NULL,
  "incident_description" TEXT NOT NULL,
  "asset_type" VARCHAR(100) NOT NULL,
  "asset_description" VARCHAR(255) NOT NULL,
  "asset_code" VARCHAR(50) NOT NULL,
  "estimated_loss" NUMERIC NOT NULL,
  "status" VARCHAR(25) NOT NULL,
  "approved_amount" NUMERIC,
  "payment_date" DATE,
  "rejection_reason" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "assigned_to_id" BIGINT,
  "policy_id" BIGINT,
  "reported_by_id" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS "claims_claimdocument" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "document_name" VARCHAR(255) NOT NULL,
  "document_type" VARCHAR(20) NOT NULL,
  "file" VARCHAR(100) NOT NULL,
  "file_size" INTEGER NOT NULL,
  "is_required" BOOLEAN NOT NULL,
  "uploaded_at" TIMESTAMPTZ NOT NULL,
  "claim_id" BIGINT NOT NULL,
  "uploaded_by_id" BIGINT NOT NULL,
  "description" TEXT NOT NULL,
  "is_latest_version" BOOLEAN NOT NULL,
  "last_modified" TIMESTAMPTZ NOT NULL,
  "mime_type" VARCHAR(100) NOT NULL,
  "required_deadline" DATE,
  "status" VARCHAR(20) NOT NULL,
  "tags" VARCHAR(500) NOT NULL,
  "version" INTEGER NOT NULL,
  "parent_document_id" BIGINT
);

CREATE TABLE IF NOT EXISTS "claims_claimsettlement" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "settlement_number" VARCHAR(50) NOT NULL,
  "claim_reference_number" VARCHAR(100) NOT NULL,
  "total_claim_amount" NUMERIC NOT NULL,
  "deductible_amount" NUMERIC NOT NULL,
  "depreciation_amount" NUMERIC NOT NULL,
  "final_payment_amount" NUMERIC NOT NULL,
  "settlement_date" DATE NOT NULL,
  "payment_date" DATE,
  "payment_reference" VARCHAR(100) NOT NULL,
  "status" VARCHAR(20) NOT NULL,
  "signed_date" DATE,
  "settlement_document" VARCHAR(100),
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "approved_by_id" BIGINT,
  "claim_id" BIGINT NOT NULL,
  "created_by_id" BIGINT
);

CREATE TABLE IF NOT EXISTS "claims_claimtimeline" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_type" VARCHAR(20) NOT NULL,
  "event_description" TEXT NOT NULL,
  "old_status" VARCHAR(25) NOT NULL,
  "new_status" VARCHAR(25) NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "claim_id" BIGINT NOT NULL,
  "created_by_id" BIGINT
);

CREATE TABLE IF NOT EXISTS "companies_emissionrights" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "min_amount" NUMERIC NOT NULL,
  "max_amount" NUMERIC NOT NULL,
  "emission_right" NUMERIC NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "created_by_id" BIGINT,
  "is_active" BOOLEAN NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "valid_from" DATE NOT NULL,
  "valid_until" DATE
);

CREATE TABLE IF NOT EXISTS "companies_insurancecompany" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "ruc" VARCHAR(13) NOT NULL,
  "address" TEXT NOT NULL,
  "phone" VARCHAR(20) NOT NULL,
  "email" VARCHAR(254) NOT NULL,
  "contact_person" VARCHAR(255) NOT NULL,
  "is_active" BOOLEAN NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "companies_policyretention" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "applies_to_premium" BOOLEAN NOT NULL,
  "applies_to_total" BOOLEAN NOT NULL,
  "custom_percentage" NUMERIC,
  "is_active" BOOLEAN NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "created_by_id" BIGINT,
  "policy_id" BIGINT NOT NULL,
  "retention_type_id" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS "companies_retentiontype" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(100) NOT NULL,
  "code" VARCHAR(20) NOT NULL,
  "retention_type" VARCHAR(20) NOT NULL,
  "percentage" NUMERIC NOT NULL,
  "is_active" BOOLEAN NOT NULL,
  "description" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "django_admin_log" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "object_id" TEXT,
  "object_repr" VARCHAR(200) NOT NULL,
  "action_flag" INTEGER NOT NULL,
  "change_message" TEXT NOT NULL,
  "content_type_id" INTEGER,
  "user_id" BIGINT NOT NULL,
  "action_time" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "django_content_type" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "app_label" VARCHAR(100) NOT NULL,
  "model" VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS "django_migrations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "app" VARCHAR(255) NOT NULL,
  "name" VARCHAR(255) NOT NULL,
  "applied" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "django_session" (
  "session_key" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "session_data" TEXT NOT NULL,
  "expire_date" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "invoices_invoice" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "invoice_number" VARCHAR(50) NOT NULL,
  "invoice_date" DATE NOT NULL,
  "due_date" DATE NOT NULL,
  "premium" NUMERIC NOT NULL,
  "superintendence_contribution" NUMERIC NOT NULL,
  "farm_insurance_contribution" NUMERIC NOT NULL,
  "emission_rights" NUMERIC NOT NULL,
  "tax_base" NUMERIC NOT NULL,
  "iva" NUMERIC NOT NULL,
  "withholding_tax" NUMERIC NOT NULL,
  "early_payment_discount" NUMERIC NOT NULL,
  "total_amount" NUMERIC NOT NULL,
  "payment_status" VARCHAR(20) NOT NULL,
  "payment_date" DATE,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "created_by_id" BIGINT NOT NULL,
  "policy_id" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS "notifications_alert" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "alert_type" VARCHAR(20) NOT NULL,
  "description" TEXT NOT NULL,
  "conditions" TEXT NOT NULL,
  "email_recipients" TEXT NOT NULL,
  "frequency" VARCHAR(10) NOT NULL,
  "is_active" BOOLEAN NOT NULL,
  "last_run" TIMESTAMPTZ,
  "next_run" TIMESTAMPTZ,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "created_by_id" BIGINT
);

CREATE TABLE IF NOT EXISTS "notifications_alert_recipients" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "alert_id" BIGINT NOT NULL,
  "userprofile_id" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS "notifications_emaillog" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "recipient_email" VARCHAR(254) NOT NULL,
  "recipient_name" VARCHAR(255) NOT NULL,
  "subject" VARCHAR(255) NOT NULL,
  "status" VARCHAR(10) NOT NULL,
  "sent_at" TIMESTAMPTZ,
  "error_message" TEXT NOT NULL,
  "context_data" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "claim_id" BIGINT,
  "created_by_id" BIGINT,
  "invoice_id" BIGINT,
  "policy_id" BIGINT,
  "template_id" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS "notifications_emailtemplate" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(100) NOT NULL,
  "template_type" VARCHAR(30) NOT NULL,
  "recipient_type" VARCHAR(20) NOT NULL,
  "subject" VARCHAR(255) NOT NULL,
  "body_html" TEXT NOT NULL,
  "body_text" TEXT NOT NULL,
  "is_active" BOOLEAN NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "created_by_id" BIGINT
);

CREATE TABLE IF NOT EXISTS "notifications_notification" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notification_type" VARCHAR(20) NOT NULL,
  "title" VARCHAR(255) NOT NULL,
  "message" TEXT NOT NULL,
  "link" VARCHAR(200) NOT NULL,
  "is_read" BOOLEAN NOT NULL,
  "priority" VARCHAR(10) NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "user_id" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS "policies_policy" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "policy_number" VARCHAR(50) NOT NULL,
  "group_type" VARCHAR(20) NOT NULL,
  "subgroup" VARCHAR(100) NOT NULL,
  "branch" VARCHAR(100) NOT NULL,
  "start_date" DATE NOT NULL,
  "end_date" DATE NOT NULL,
  "issue_date" DATE,
  "insured_value" NUMERIC NOT NULL,
  "coverage_description" TEXT NOT NULL,
  "observations" TEXT NOT NULL,
  "status" VARCHAR(20) NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "broker_id" BIGINT,
  "insurance_company_id" BIGINT NOT NULL,
  "responsible_user_id" BIGINT
);

CREATE TABLE IF NOT EXISTS "policies_policydocument" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "document_name" VARCHAR(255) NOT NULL,
  "document_type" VARCHAR(20) NOT NULL,
  "file" VARCHAR(100) NOT NULL,
  "file_size" INTEGER NOT NULL,
  "uploaded_at" TIMESTAMPTZ NOT NULL,
  "policy_id" BIGINT NOT NULL,
  "uploaded_by_id" BIGINT NOT NULL,
  "description" TEXT NOT NULL,
  "is_latest_version" BOOLEAN NOT NULL,
  "last_modified" TIMESTAMPTZ NOT NULL,
  "mime_type" VARCHAR(100) NOT NULL,
  "status" VARCHAR(20) NOT NULL,
  "tags" VARCHAR(500) NOT NULL,
  "version" INTEGER NOT NULL,
  "parent_document_id" BIGINT
);

CREATE TABLE IF NOT EXISTS "reports_report" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "report_type" VARCHAR(50) NOT NULL,
  "description" TEXT NOT NULL,
  "filters" TEXT NOT NULL,
  "parameters" TEXT NOT NULL,
  "is_scheduled" BOOLEAN NOT NULL,
  "schedule_frequency" VARCHAR(20) NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  "last_run" TIMESTAMPTZ,
  "created_by_id" BIGINT
);

CREATE TABLE IF NOT EXISTS "reports_report_recipients" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "report_id" BIGINT NOT NULL,
  "userprofile_id" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS "reports_reportexecution" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "executed_at" TIMESTAMPTZ NOT NULL,
  "execution_time_seconds" DOUBLE PRECISION NOT NULL,
  "success" BOOLEAN NOT NULL,
  "error_message" TEXT NOT NULL,
  "export_format" VARCHAR(10) NOT NULL,
  "exported_file" VARCHAR(100),
  "executed_by_id" BIGINT,
  "report_id" BIGINT NOT NULL
);
ALTER TABLE "accounts_userprofile_groups" ADD CONSTRAINT "fk_accounts_userprofile_groups_group_id_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "accounts_userprofile_groups" ADD CONSTRAINT "fk_accounts_userprofile_groups_userprofile_id_accounts_userprofile_id" FOREIGN KEY ("userprofile_id") REFERENCES "accounts_userprofile" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "accounts_userprofile_user_permissions" ADD CONSTRAINT "fk_accounts_userprofile_user_permissions_permission_id_auth_permission_id" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "accounts_userprofile_user_permissions" ADD CONSTRAINT "fk_accounts_userprofile_user_permissions_userprofile_id_accounts_userprofile_id" FOREIGN KEY ("userprofile_id") REFERENCES "accounts_userprofile" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "assets_asset" ADD CONSTRAINT "fk_assets_asset_responsible_user_id_accounts_userprofile_id" FOREIGN KEY ("responsible_user_id") REFERENCES "accounts_userprofile" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "assets_asset" ADD CONSTRAINT "fk_assets_asset_insurance_policy_id_policies_policy_id" FOREIGN KEY ("insurance_policy_id") REFERENCES "policies_policy" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "assets_asset" ADD CONSTRAINT "fk_assets_asset_custodian_id_accounts_userprofile_id" FOREIGN KEY ("custodian_id") REFERENCES "accounts_userprofile" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "audit_auditlog" ADD CONSTRAINT "fk_audit_auditlog_user_id_accounts_userprofile_id" FOREIGN KEY ("user_id") REFERENCES "accounts_userprofile" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "audit_auditlog" ADD CONSTRAINT "fk_audit_auditlog_content_type_id_django_content_type_id" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "fk_auth_group_permissions_permission_id_auth_permission_id" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "fk_auth_group_permissions_group_id_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "auth_permission" ADD CONSTRAINT "fk_auth_permission_content_type_id_django_content_type_id" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "claims_claim" ADD CONSTRAINT "fk_claims_claim_reported_by_id_accounts_userprofile_id" FOREIGN KEY ("reported_by_id") REFERENCES "accounts_userprofile" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "claims_claim" ADD CONSTRAINT "fk_claims_claim_policy_id_policies_policy_id" FOREIGN KEY ("policy_id") REFERENCES "policies_policy" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "claims_claim" ADD CONSTRAINT "fk_claims_claim_assigned_to_id_accounts_userprofile_id" FOREIGN KEY ("assigned_to_id") REFERENCES "accounts_userprofile" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "claims_claimdocument" ADD CONSTRAINT "fk_claims_claimdocument_parent_document_id_claims_claimdocument_id" FOREIGN KEY ("parent_document_id") REFERENCES "claims_claimdocument" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "claims_claimdocument" ADD CONSTRAINT "fk_claims_claimdocument_uploaded_by_id_accounts_userprofile_id" FOREIGN KEY ("uploaded_by_id") REFERENCES "accounts_userprofile" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "claims_claimdocument" ADD CONSTRAINT "fk_claims_claimdocument_claim_id_claims_claim_id" FOREIGN KEY ("claim_id") REFERENCES "claims_claim" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "claims_claimsettlement" ADD CONSTRAINT "fk_claims_claimsettlement_created_by_id_accounts_userprofile_id" FOREIGN KEY ("created_by_id") REFERENCES "accounts_userprofile" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "claims_claimsettlement" ADD CONSTRAINT "fk_claims_claimsettlement_claim_id_claims_claim_id" FOREIGN KEY ("claim_id") REFERENCES "claims_claim" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "claims_claimsettlement" ADD CONSTRAINT "fk_claims_claimsettlement_approved_by_id_accounts_userprofile_id" FOREIGN KEY ("approved_by_id") REFERENCES "accounts_userprofile" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "claims_claimtimeline" ADD CONSTRAINT "fk_claims_claimtimeline_created_by_id_accounts_userprofile_id" FOREIGN KEY ("created_by_id") REFERENCES "accounts_userprofile" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "claims_claimtimeline" ADD CONSTRAINT "fk_claims_claimtimeline_claim_id_claims_claim_id" FOREIGN KEY ("claim_id") REFERENCES "claims_claim" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "companies_emissionrights" ADD CONSTRAINT "fk_companies_emissionrights_created_by_id_accounts_userprofile_id" FOREIGN KEY ("created_by_id") REFERENCES "accounts_userprofile" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "companies_policyretention" ADD CONSTRAINT "fk_companies_policyretention_retention_type_id_companies_retentiontype_id" FOREIGN KEY ("retention_type_id") REFERENCES "companies_retentiontype" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "companies_policyretention" ADD CONSTRAINT "fk_companies_policyretention_policy_id_policies_policy_id" FOREIGN KEY ("policy_id") REFERENCES "policies_policy" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "companies_policyretention" ADD CONSTRAINT "fk_companies_policyretention_created_by_id_accounts_userprofile_id" FOREIGN KEY ("created_by_id") REFERENCES "accounts_userprofile" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "django_admin_log" ADD CONSTRAINT "fk_django_admin_log_user_id_accounts_userprofile_id" FOREIGN KEY ("user_id") REFERENCES "accounts_userprofile" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "django_admin_log" ADD CONSTRAINT "fk_django_admin_log_content_type_id_django_content_type_id" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "invoices_invoice" ADD CONSTRAINT "fk_invoices_invoice_policy_id_policies_policy_id" FOREIGN KEY ("policy_id") REFERENCES "policies_policy" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "invoices_invoice" ADD CONSTRAINT "fk_invoices_invoice_created_by_id_accounts_userprofile_id" FOREIGN KEY ("created_by_id") REFERENCES "accounts_userprofile" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "notifications_alert" ADD CONSTRAINT "fk_notifications_alert_created_by_id_accounts_userprofile_id" FOREIGN KEY ("created_by_id") REFERENCES "accounts_userprofile" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "notifications_alert_recipients" ADD CONSTRAINT "fk_notifications_alert_recipients_userprofile_id_accounts_userprofile_id" FOREIGN KEY ("userprofile_id") REFERENCES "accounts_userprofile" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "notifications_alert_recipients" ADD CONSTRAINT "fk_notifications_alert_recipients_alert_id_notifications_alert_id" FOREIGN KEY ("alert_id") REFERENCES "notifications_alert" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "notifications_emaillog" ADD CONSTRAINT "fk_notifications_emaillog_template_id_notifications_emailtemplate_id" FOREIGN KEY ("template_id") REFERENCES "notifications_emailtemplate" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "notifications_emaillog" ADD CONSTRAINT "fk_notifications_emaillog_policy_id_policies_policy_id" FOREIGN KEY ("policy_id") REFERENCES "policies_policy" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "notifications_emaillog" ADD CONSTRAINT "fk_notifications_emaillog_invoice_id_invoices_invoice_id" FOREIGN KEY ("invoice_id") REFERENCES "invoices_invoice" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "notifications_emaillog" ADD CONSTRAINT "fk_notifications_emaillog_created_by_id_accounts_userprofile_id" FOREIGN KEY ("created_by_id") REFERENCES "accounts_userprofile" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "notifications_emaillog" ADD CONSTRAINT "fk_notifications_emaillog_claim_id_claims_claim_id" FOREIGN KEY ("claim_id") REFERENCES "claims_claim" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "notifications_emailtemplate" ADD CONSTRAINT "fk_notifications_emailtemplate_created_by_id_accounts_userprofile_id" FOREIGN KEY ("created_by_id") REFERENCES "accounts_userprofile" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "notifications_notification" ADD CONSTRAINT "fk_notifications_notification_user_id_accounts_userprofile_id" FOREIGN KEY ("user_id") REFERENCES "accounts_userprofile" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "policies_policy" ADD CONSTRAINT "fk_policies_policy_responsible_user_id_accounts_userprofile_id" FOREIGN KEY ("responsible_user_id") REFERENCES "accounts_userprofile" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "policies_policy" ADD CONSTRAINT "fk_policies_policy_insurance_company_id_companies_insurancecompany_id" FOREIGN KEY ("insurance_company_id") REFERENCES "companies_insurancecompany" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "policies_policy" ADD CONSTRAINT "fk_policies_policy_broker_id_brokers_broker_id" FOREIGN KEY ("broker_id") REFERENCES "brokers_broker" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "policies_policydocument" ADD CONSTRAINT "fk_policies_policydocument_parent_document_id_policies_policydocument_id" FOREIGN KEY ("parent_document_id") REFERENCES "policies_policydocument" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "policies_policydocument" ADD CONSTRAINT "fk_policies_policydocument_uploaded_by_id_accounts_userprofile_id" FOREIGN KEY ("uploaded_by_id") REFERENCES "accounts_userprofile" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "policies_policydocument" ADD CONSTRAINT "fk_policies_policydocument_policy_id_policies_policy_id" FOREIGN KEY ("policy_id") REFERENCES "policies_policy" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "reports_report" ADD CONSTRAINT "fk_reports_report_created_by_id_accounts_userprofile_id" FOREIGN KEY ("created_by_id") REFERENCES "accounts_userprofile" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "reports_report_recipients" ADD CONSTRAINT "fk_reports_report_recipients_userprofile_id_accounts_userprofile_id" FOREIGN KEY ("userprofile_id") REFERENCES "accounts_userprofile" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "reports_report_recipients" ADD CONSTRAINT "fk_reports_report_recipients_report_id_reports_report_id" FOREIGN KEY ("report_id") REFERENCES "reports_report" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "reports_reportexecution" ADD CONSTRAINT "fk_reports_reportexecution_report_id_reports_report_id" FOREIGN KEY ("report_id") REFERENCES "reports_report" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "reports_reportexecution" ADD CONSTRAINT "fk_reports_reportexecution_executed_by_id_accounts_userprofile_id" FOREIGN KEY ("executed_by_id") REFERENCES "accounts_userprofile" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- Indexes (translated from SQLite)
CREATE INDEX IF NOT EXISTS "accounts_userprofile_groups_group_id_74ae51cf" ON "accounts_userprofile_groups" ("group_id");
CREATE INDEX IF NOT EXISTS "accounts_userprofile_groups_userprofile_id_b7fb6469" ON "accounts_userprofile_groups" ("userprofile_id");
CREATE UNIQUE INDEX IF NOT EXISTS "accounts_userprofile_groups_userprofile_id_group_id_36cd9fa6_uniq" ON "accounts_userprofile_groups" ("userprofile_id", "group_id");
CREATE INDEX IF NOT EXISTS "accounts_userprofile_user_permissions_permission_id_a9b2b32b" ON "accounts_userprofile_user_permissions" ("permission_id");
CREATE INDEX IF NOT EXISTS "accounts_userprofile_user_permissions_userprofile_id_4acaf5a0" ON "accounts_userprofile_user_permissions" ("userprofile_id");
CREATE UNIQUE INDEX IF NOT EXISTS "accounts_userprofile_user_permissions_userprofile_id_permission_id_22053107_uniq" ON "accounts_userprofile_user_permissions" ("userprofile_id", "permission_id");
CREATE INDEX IF NOT EXISTS "assets_asset_custodian_id_cf597733" ON "assets_asset" ("custodian_id");
CREATE INDEX IF NOT EXISTS "assets_asset_insurance_policy_id_4f2572ea" ON "assets_asset" ("insurance_policy_id");
CREATE INDEX IF NOT EXISTS "assets_asset_responsible_user_id_71844a64" ON "assets_asset" ("responsible_user_id");
CREATE INDEX IF NOT EXISTS "audit_audit_action__4cc9ae_idx" ON "audit_auditlog" ("action_type", "created_at" DESC);
CREATE INDEX IF NOT EXISTS "audit_audit_created_6e540c_idx" ON "audit_auditlog" ("created_at" DESC);
CREATE INDEX IF NOT EXISTS "audit_audit_entity__9535bf_idx" ON "audit_auditlog" ("entity_type", "entity_id");
CREATE INDEX IF NOT EXISTS "audit_audit_user_id_429f6b_idx" ON "audit_auditlog" ("user_id", "created_at" DESC);
CREATE INDEX IF NOT EXISTS "audit_auditlog_content_type_id_61188c00" ON "audit_auditlog" ("content_type_id");
CREATE INDEX IF NOT EXISTS "audit_auditlog_user_id_c1cca96c" ON "audit_auditlog" ("user_id");
CREATE INDEX IF NOT EXISTS "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE UNIQUE INDEX IF NOT EXISTS "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX IF NOT EXISTS "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE INDEX IF NOT EXISTS "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE UNIQUE INDEX IF NOT EXISTS "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX IF NOT EXISTS "claims_claim_assigned_to_id_5e597702" ON "claims_claim" ("assigned_to_id");
CREATE INDEX IF NOT EXISTS "claims_claim_policy_id_5de3076f" ON "claims_claim" ("policy_id");
CREATE INDEX IF NOT EXISTS "claims_claim_reported_by_id_84ccc0c2" ON "claims_claim" ("reported_by_id");
CREATE INDEX IF NOT EXISTS "claims_claimdocument_claim_id_c1c69bf4" ON "claims_claimdocument" ("claim_id");
CREATE UNIQUE INDEX IF NOT EXISTS "claims_claimdocument_claim_id_document_name_version_81b57565_uniq" ON "claims_claimdocument" ("claim_id", "document_name", "version");
CREATE INDEX IF NOT EXISTS "claims_claimdocument_parent_document_id_c4c866cb" ON "claims_claimdocument" ("parent_document_id");
CREATE INDEX IF NOT EXISTS "claims_claimdocument_uploaded_by_id_d349eab2" ON "claims_claimdocument" ("uploaded_by_id");
CREATE INDEX IF NOT EXISTS "claims_claimsettlement_approved_by_id_87227610" ON "claims_claimsettlement" ("approved_by_id");
CREATE INDEX IF NOT EXISTS "claims_claimsettlement_created_by_id_1a93ee08" ON "claims_claimsettlement" ("created_by_id");
CREATE INDEX IF NOT EXISTS "claims_claimtimeline_claim_id_6b316b05" ON "claims_claimtimeline" ("claim_id");
CREATE INDEX IF NOT EXISTS "claims_claimtimeline_created_by_id_b3ba08d9" ON "claims_claimtimeline" ("created_by_id");
CREATE INDEX IF NOT EXISTS "companies_emissionrights_created_by_id_9a987c04" ON "companies_emissionrights" ("created_by_id");
CREATE INDEX IF NOT EXISTS "companies_policyretention_created_by_id_08e1829c" ON "companies_policyretention" ("created_by_id");
CREATE INDEX IF NOT EXISTS "companies_policyretention_policy_id_75b5d44c" ON "companies_policyretention" ("policy_id");
CREATE UNIQUE INDEX IF NOT EXISTS "companies_policyretention_policy_id_retention_type_id_54803af0_uniq" ON "companies_policyretention" ("policy_id", "retention_type_id");
CREATE INDEX IF NOT EXISTS "companies_policyretention_retention_type_id_da403691" ON "companies_policyretention" ("retention_type_id");
CREATE INDEX IF NOT EXISTS "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX IF NOT EXISTS "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE INDEX IF NOT EXISTS "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE INDEX IF NOT EXISTS "invoices_invoice_created_by_id_9b878bcd" ON "invoices_invoice" ("created_by_id");
CREATE INDEX IF NOT EXISTS "invoices_invoice_policy_id_b9328214" ON "invoices_invoice" ("policy_id");
CREATE INDEX IF NOT EXISTS "notifications_alert_created_by_id_20c44c8c" ON "notifications_alert" ("created_by_id");
CREATE INDEX IF NOT EXISTS "notifications_alert_recipients_alert_id_1ebca1fd" ON "notifications_alert_recipients" ("alert_id");
CREATE UNIQUE INDEX IF NOT EXISTS "notifications_alert_recipients_alert_id_userprofile_id_0f3782c9_uniq" ON "notifications_alert_recipients" ("alert_id", "userprofile_id");
CREATE INDEX IF NOT EXISTS "notifications_alert_recipients_userprofile_id_26c713a9" ON "notifications_alert_recipients" ("userprofile_id");
CREATE INDEX IF NOT EXISTS "notificatio_recipie_25af1a_idx" ON "notifications_emaillog" ("recipient_email");
CREATE INDEX IF NOT EXISTS "notificatio_status_6192b4_idx" ON "notifications_emaillog" ("status", "created_at");
CREATE INDEX IF NOT EXISTS "notifications_emaillog_claim_id_a6cdd0e6" ON "notifications_emaillog" ("claim_id");
CREATE INDEX IF NOT EXISTS "notifications_emaillog_created_by_id_7bdaad6b" ON "notifications_emaillog" ("created_by_id");
CREATE INDEX IF NOT EXISTS "notifications_emaillog_invoice_id_fb0a7a17" ON "notifications_emaillog" ("invoice_id");
CREATE INDEX IF NOT EXISTS "notifications_emaillog_policy_id_ac1160a2" ON "notifications_emaillog" ("policy_id");
CREATE INDEX IF NOT EXISTS "notifications_emaillog_template_id_276b6a99" ON "notifications_emaillog" ("template_id");
CREATE INDEX IF NOT EXISTS "notifications_emailtemplate_created_by_id_3a9e3e29" ON "notifications_emailtemplate" ("created_by_id");
CREATE INDEX IF NOT EXISTS "notificatio_is_read_584b29_idx" ON "notifications_notification" ("is_read", "priority");
CREATE INDEX IF NOT EXISTS "notificatio_user_id_05b4bc_idx" ON "notifications_notification" ("user_id", "created_at" DESC);
CREATE INDEX IF NOT EXISTS "notifications_notification_user_id_b5e8c0ff" ON "notifications_notification" ("user_id");
CREATE INDEX IF NOT EXISTS "policies_policy_broker_id_c00b80b4" ON "policies_policy" ("broker_id");
CREATE INDEX IF NOT EXISTS "policies_policy_insurance_company_id_102a3289" ON "policies_policy" ("insurance_company_id");
CREATE INDEX IF NOT EXISTS "policies_policy_responsible_user_id_1eb4db67" ON "policies_policy" ("responsible_user_id");
CREATE INDEX IF NOT EXISTS "policies_policydocument_parent_document_id_3141195e" ON "policies_policydocument" ("parent_document_id");
CREATE UNIQUE INDEX IF NOT EXISTS "policies_policydocument_policy_id_document_name_version_3a1d6ec7_uniq" ON "policies_policydocument" ("policy_id", "document_name", "version");
CREATE INDEX IF NOT EXISTS "policies_policydocument_policy_id_e99d5e70" ON "policies_policydocument" ("policy_id");
CREATE INDEX IF NOT EXISTS "policies_policydocument_uploaded_by_id_12f28527" ON "policies_policydocument" ("uploaded_by_id");
CREATE INDEX IF NOT EXISTS "reports_report_created_by_id_e9adac24" ON "reports_report" ("created_by_id");
CREATE INDEX IF NOT EXISTS "reports_report_recipients_report_id_9c8abe54" ON "reports_report_recipients" ("report_id");
CREATE UNIQUE INDEX IF NOT EXISTS "reports_report_recipients_report_id_userprofile_id_bb0d479c_uniq" ON "reports_report_recipients" ("report_id", "userprofile_id");
CREATE INDEX IF NOT EXISTS "reports_report_recipients_userprofile_id_ea4342d8" ON "reports_report_recipients" ("userprofile_id");
CREATE INDEX IF NOT EXISTS "reports_reportexecution_executed_by_id_feb8b69e" ON "reports_reportexecution" ("executed_by_id");
CREATE INDEX IF NOT EXISTS "reports_reportexecution_report_id_0406ed5a" ON "reports_reportexecution" ("report_id");

COMMIT;