# Generated by Django 5.1.7 on 2026-01-04 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("brokers", "0001_initial"),
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de póliza"
                    ),
                ),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("patrimoniales", "Patrimoniales"),
                            ("personas", "Personas"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de grupo",
                    ),
                ),
                ("subgroup", models.CharField(max_length=100, verbose_name="Subgrupo")),
                ("branch", models.CharField(max_length=100, verbose_name="Rama")),
                ("start_date", models.DateField(verbose_name="Fecha de inicio")),
                ("end_date", models.DateField(verbose_name="Fecha de fin")),
                (
                    "issue_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de emisión"
                    ),
                ),
                (
                    "insured_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Valor asegurado"
                    ),
                ),
                (
                    "coverage_description",
                    models.TextField(
                        blank=True, verbose_name="Descripción de cobertura"
                    ),
                ),
                (
                    "observations",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activa"),
                            ("expired", "Vencida"),
                            ("cancelled", "Cancelada"),
                            ("renewed", "Renovada"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "broker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="policies",
                        to="brokers.broker",
                        verbose_name="Corredor",
                    ),
                ),
                (
                    "insurance_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policies",
                        to="companies.insurancecompany",
                        verbose_name="Compañía de seguros",
                    ),
                ),
                (
                    "responsible_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsible_policies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Póliza",
                "verbose_name_plural": "Pólizas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PolicyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del documento"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("policy", "Póliza"),
                            ("endorsement", "Endoso"),
                            ("certificate", "Certificado"),
                            ("receipt", "Recibo"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="policies/documents/%Y/%m/", verbose_name="Archivo"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        editable=False, verbose_name="Tamaño del archivo"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de subida"
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="policies.policy",
                        verbose_name="Póliza",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_policy_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Subido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Póliza",
                "verbose_name_plural": "Documentos de Póliza",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
