# Generated by Django 5.1.7 on 2026-01-19 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("policies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de factura"
                    ),
                ),
                ("invoice_date", models.DateField(verbose_name="Fecha de factura")),
                ("due_date", models.DateField(verbose_name="Fecha de vencimiento")),
                (
                    "premium",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=15,
                        verbose_name="Prima base",
                    ),
                ),
                (
                    "superintendence_contribution",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=15,
                        verbose_name="Contribución Superintendencia (3.5%)",
                    ),
                ),
                (
                    "farm_insurance_contribution",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=15,
                        verbose_name="Contribución Seguro Campesino (0.5%)",
                    ),
                ),
                (
                    "emission_rights",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=15,
                        verbose_name="Derechos de emisión",
                    ),
                ),
                (
                    "tax_base",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=15,
                        verbose_name="Base imponible",
                    ),
                ),
                (
                    "iva",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=15,
                        verbose_name="IVA (15%)",
                    ),
                ),
                (
                    "withholding_tax",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Retenciones",
                    ),
                ),
                (
                    "early_payment_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=15,
                        verbose_name="Descuento pronto pago (5%)",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=15,
                        verbose_name="Total final",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("pagada", "Pagada"),
                            ("pagada_pronto_pago", "Pagada con descuento pronto pago"),
                            ("vencida", "Vencida"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=25,
                        verbose_name="Estado de pago",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha en que se realizó el pago",
                        null=True,
                        verbose_name="Fecha de pago real",
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        help_text="Fecha límite para el pago",
                        verbose_name="Fecha de vencimiento",
                    ),
                ),
                (
                    "documento_contable",
                    models.CharField(
                        blank=True,
                        help_text="Número de documento contable o comprobante",
                        max_length=100,
                        verbose_name="Documento contable",
                    ),
                ),
                (
                    "descuento_pronto_pago_aplicado",
                    models.BooleanField(
                        default=False,
                        help_text="Si se aplicó el descuento del 5% por pronto pago",
                        verbose_name="Descuento pronto pago aplicado",
                    ),
                ),
                (
                    "descuento_pronto_pago_valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monto del descuento aplicado (5% sobre prima)",
                        max_digits=15,
                        verbose_name="Valor descuento pronto pago",
                    ),
                ),
                (
                    "dias_desde_emision",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Días transcurridos desde la emisión (calculado)",
                        verbose_name="Días desde emisión",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="policies.policy",
                        verbose_name="Póliza",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura",
                "verbose_name_plural": "Facturas",
                "ordering": ["-created_at"],
            },
        ),
    ]
