# Generated by Django 5.1.7 on 2026-01-04 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("policies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de factura"
                    ),
                ),
                ("invoice_date", models.DateField(verbose_name="Fecha de factura")),
                ("due_date", models.DateField(verbose_name="Fecha de vencimiento")),
                (
                    "premium",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=15,
                        verbose_name="Prima base",
                    ),
                ),
                (
                    "superintendence_contribution",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=15,
                        verbose_name="Contribución Superintendencia (3.5%)",
                    ),
                ),
                (
                    "farm_insurance_contribution",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=15,
                        verbose_name="Contribución Seguro Campesino (0.5%)",
                    ),
                ),
                (
                    "emission_rights",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=15,
                        verbose_name="Derechos de emisión",
                    ),
                ),
                (
                    "tax_base",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=15,
                        verbose_name="Base imponible",
                    ),
                ),
                (
                    "iva",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=15,
                        verbose_name="IVA (15%)",
                    ),
                ),
                (
                    "withholding_tax",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Retenciones",
                    ),
                ),
                (
                    "early_payment_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=15,
                        verbose_name="Descuento pronto pago (5%)",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=15,
                        verbose_name="Total final",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("paid", "Pagada"),
                            ("overdue", "Vencida"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado de pago",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de pago"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="policies.policy",
                        verbose_name="Póliza",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura",
                "verbose_name_plural": "Facturas",
                "ordering": ["-created_at"],
            },
        ),
    ]
