# Generated by Django 5.1.7 on 2026-01-04 17:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("policies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "claim_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de siniestro"
                    ),
                ),
                ("incident_date", models.DateField(verbose_name="Fecha del incidente")),
                ("report_date", models.DateField(verbose_name="Fecha de reporte")),
                (
                    "incident_location",
                    models.CharField(
                        max_length=255, verbose_name="Ubicación del incidente"
                    ),
                ),
                (
                    "incident_description",
                    models.TextField(verbose_name="Descripción del incidente"),
                ),
                (
                    "asset_type",
                    models.CharField(
                        max_length=100, verbose_name="Tipo de bien afectado"
                    ),
                ),
                (
                    "asset_description",
                    models.CharField(
                        max_length=255, verbose_name="Descripción del bien"
                    ),
                ),
                (
                    "asset_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Código del bien"
                    ),
                ),
                (
                    "estimated_loss",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Pérdida estimada",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Reportado"),
                            ("documentation_pending", "Documentación pendiente"),
                            ("sent_to_insurer", "Enviado a aseguradora"),
                            ("under_evaluation", "En evaluación"),
                            ("liquidated", "Liquidado"),
                            ("paid", "Pagado"),
                            ("closed", "Cerrado"),
                            ("rejected", "Rechazado"),
                        ],
                        default="reported",
                        max_length=25,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "approved_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Monto aprobado",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de pago"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Razón de rechazo"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_claims",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asignado a",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claims",
                        to="policies.policy",
                        verbose_name="Póliza",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reported_claims",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reportado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Siniestro",
                "verbose_name_plural": "Siniestros",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClaimDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del documento"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("initial_report", "Reporte inicial"),
                            ("photos", "Fotos"),
                            ("police_report", "Reporte policial"),
                            ("appraisal", "Avalúo"),
                            ("invoice", "Factura"),
                            ("settlement", "Finiquito"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="claims/documents/%Y/%m/", verbose_name="Archivo"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        editable=False, verbose_name="Tamaño del archivo"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="¿Es requerido?"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de subida"
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="claims.claim",
                        verbose_name="Siniestro",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_claim_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Subido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Siniestro",
                "verbose_name_plural": "Documentos de Siniestro",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ClaimTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("status_change", "Cambio de estado"),
                            ("document_uploaded", "Documento subido"),
                            ("comment", "Comentario"),
                            ("alert_sent", "Alerta enviada"),
                            ("payment_received", "Pago recibido"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de evento",
                    ),
                ),
                (
                    "event_description",
                    models.TextField(verbose_name="Descripción del evento"),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True, max_length=25, verbose_name="Estado anterior"
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True, max_length=25, verbose_name="Estado nuevo"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="claims.claim",
                        verbose_name="Siniestro",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timeline_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada de Timeline",
                "verbose_name_plural": "Timeline de Siniestros",
                "ordering": ["created_at"],
            },
        ),
    ]
