# Generated by Django 5.1.7 on 2026-01-19 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("brokers", "0001_initial"),
        ("claims", "0001_initial"),
        ("companies", "0001_initial"),
        ("policies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="aseguradora_notificada",
            field=models.ForeignKey(
                blank=True,
                help_text="Aseguradora a la que se notificó",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="companies.insurancecompany",
                verbose_name="Aseguradora notificada",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_claims",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Asignado a",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="broker_notificado",
            field=models.ForeignKey(
                blank=True,
                help_text="Broker al que se notificó el siniestro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="brokers.broker",
                verbose_name="Broker notificado",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="cobertura_aplicada",
            field=models.ForeignKey(
                blank=True,
                help_text="Cobertura de la póliza que aplica a este siniestro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="siniestros",
                to="policies.coverage",
                verbose_name="Cobertura aplicada",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claims",
                to="policies.policy",
                verbose_name="Póliza",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="reportante",
            field=models.ForeignKey(
                help_text="Usuario que reporta el siniestro",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="siniestros_reportados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reportante",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="reported_by",
            field=models.ForeignKey(
                help_text="Alias para reportante (compatibilidad)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reported_claims",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reportado por",
            ),
        ),
        migrations.AddField(
            model_name="claimdocument",
            name="claim",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="claims.claim",
                verbose_name="Siniestro",
            ),
        ),
        migrations.AddField(
            model_name="claimdocument",
            name="parent_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versions",
                to="claims.claimdocument",
                verbose_name="Documento padre",
            ),
        ),
        migrations.AddField(
            model_name="claimdocument",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uploaded_claim_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Subido por",
            ),
        ),
        migrations.AddField(
            model_name="claimsettlement",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="settlements_approved",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aprobado por",
            ),
        ),
        migrations.AddField(
            model_name="claimsettlement",
            name="claim",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settlement",
                to="claims.claim",
                verbose_name="Siniestro",
            ),
        ),
        migrations.AddField(
            model_name="claimsettlement",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="settlements_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="claimtimeline",
            name="claim",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeline",
                to="claims.claim",
                verbose_name="Siniestro",
            ),
        ),
        migrations.AddField(
            model_name="claimtimeline",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timeline_entries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="claimdocument",
            unique_together={("claim", "document_name", "version")},
        ),
    ]
