# Generated by Django 5.1.7 on 2026-01-04 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaimSettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "settlement_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Número de Finiquito",
                    ),
                ),
                (
                    "claim_reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Número de referencia del reclamo en la aseguradora",
                        max_length=100,
                        verbose_name="Número de Reclamo",
                    ),
                ),
                (
                    "total_claim_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monto total aprobado por la aseguradora",
                        max_digits=12,
                        verbose_name="Valor Total del Reclamo",
                    ),
                ),
                (
                    "deductible_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monto del deducible aplicado",
                        max_digits=12,
                        verbose_name="Deducible Aplicado",
                    ),
                ),
                (
                    "depreciation_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Valor de depreciación aplicado",
                        max_digits=12,
                        verbose_name="Depreciación",
                    ),
                ),
                (
                    "final_payment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monto final que se pagará al asegurado",
                        max_digits=12,
                        verbose_name="Valor Final a Pagar",
                    ),
                ),
                (
                    "settlement_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Finiquito"
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Pago"
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Referencia de Pago"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("pending_approval", "Pendiente de Aprobación"),
                            ("approved", "Aprobado"),
                            ("signed", "Firmado"),
                            ("paid", "Pagado"),
                            ("rejected", "Rechazado"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "signed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Firma"
                    ),
                ),
                (
                    "settlement_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="settlements/",
                        verbose_name="Documento de Finiquito",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settlements_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobado por",
                    ),
                ),
                (
                    "claim",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement",
                        to="claims.claim",
                        verbose_name="Siniestro",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settlements_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Finiquito",
                "verbose_name_plural": "Finiquitos",
                "ordering": ["-created_at"],
            },
        ),
    ]
