# Generated by Django 5.1.7 on 2026-01-04 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0002_claimsettlement"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimdocument",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descripción"),
        ),
        migrations.AddField(
            model_name="claimdocument",
            name="is_latest_version",
            field=models.BooleanField(
                default=True, verbose_name="Es la versión más reciente"
            ),
        ),
        migrations.AddField(
            model_name="claimdocument",
            name="last_modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Última modificación"
            ),
        ),
        migrations.AddField(
            model_name="claimdocument",
            name="mime_type",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Tipo MIME"
            ),
        ),
        migrations.AddField(
            model_name="claimdocument",
            name="parent_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versions",
                to="claims.claimdocument",
                verbose_name="Documento padre",
            ),
        ),
        migrations.AddField(
            model_name="claimdocument",
            name="required_deadline",
            field=models.DateField(
                blank=True,
                help_text="Fecha límite para subir este documento requerido",
                null=True,
                verbose_name="Fecha límite",
            ),
        ),
        migrations.AddField(
            model_name="claimdocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Activo"),
                    ("archived", "Archivado"),
                    ("deleted", "Eliminado"),
                ],
                default="active",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AddField(
            model_name="claimdocument",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Etiquetas separadas por comas",
                max_length=500,
                verbose_name="Etiquetas",
            ),
        ),
        migrations.AddField(
            model_name="claimdocument",
            name="version",
            field=models.PositiveIntegerField(default=1, verbose_name="Versión"),
        ),
        migrations.AlterUniqueTogether(
            name="claimdocument",
            unique_together={("claim", "document_name", "version")},
        ),
    ]
