# Generated by Django 5.1.7 on 2026-01-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0003_claim_asset"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimtimeline",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Notas adicionales sobre el cambio de estado",
                verbose_name="Notas/Observaciones",
            ),
        ),
    ]
