# Generated by Django 5.1.7 on 2026-01-19 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nombre del Reporte"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("policies_summary", "Resumen de Pólizas"),
                            ("policies_expiring", "Pólizas por Vencer"),
                            ("claims_summary", "Resumen de Siniestros"),
                            ("claims_by_cause", "Siniestros por Causa"),
                            ("financial_summary", "Resumen Financiero"),
                            ("assets_summary", "Resumen de Bienes"),
                            ("performance_metrics", "Métricas de Rendimiento"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Reporte",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "filters",
                    models.JSONField(blank=True, default=dict, verbose_name="Filtros"),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Parámetros"
                    ),
                ),
                (
                    "is_scheduled",
                    models.BooleanField(default=False, verbose_name="Programado"),
                ),
                (
                    "schedule_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("daily", "Diario"),
                            ("weekly", "Semanal"),
                            ("monthly", "Mensual"),
                        ],
                        max_length=20,
                        verbose_name="Frecuencia",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última ejecución"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        blank=True,
                        related_name="scheduled_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinatarios",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte",
                "verbose_name_plural": "Reportes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de ejecución"
                    ),
                ),
                (
                    "execution_time_seconds",
                    models.FloatField(verbose_name="Tiempo de ejecución (segundos)"),
                ),
                ("success", models.BooleanField(default=True, verbose_name="Éxito")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensaje de error"),
                ),
                (
                    "export_format",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("html", "HTML"),
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                        ],
                        max_length=10,
                        verbose_name="Formato de exportación",
                    ),
                ),
                (
                    "exported_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reports/exports/%Y/%m/",
                        verbose_name="Archivo exportado",
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_executions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ejecutado por",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="reports.report",
                        verbose_name="Reporte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ejecución de Reporte",
                "verbose_name_plural": "Ejecuciones de Reportes",
                "ordering": ["-executed_at"],
            },
        ),
    ]
