# Generated by Django 5.1.7 on 2026-01-04 17:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create", "Crear"),
                            ("update", "Actualizar"),
                            ("delete", "Eliminar"),
                            ("login", "Inicio de sesión"),
                            ("logout", "Cierre de sesión"),
                            ("export", "Exportación"),
                            ("status_change", "Cambio de estado"),
                            ("payment", "Pago"),
                            ("document_upload", "Subida de documento"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de acción",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("policy", "Póliza"),
                            ("claim", "Siniestro"),
                            ("invoice", "Factura"),
                            ("asset", "Activo"),
                            ("user", "Usuario"),
                            ("insurance_company", "Compañía aseguradora"),
                            ("broker", "Corredor"),
                            ("notification", "Notificación"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de entidad",
                    ),
                ),
                (
                    "entity_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="ID de la entidad",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "old_values",
                    models.JSONField(
                        blank=True,
                        help_text="JSON con los valores anteriores del registro",
                        null=True,
                        verbose_name="Valores anteriores",
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True,
                        help_text="JSON con los valores nuevos del registro",
                        null=True,
                        verbose_name="Valores nuevos",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descripción detallada de la acción realizada",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="Información del navegador/dispositivo del usuario",
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoría",
                "verbose_name_plural": "Logs de Auditoría",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="audit_audit_user_id_429f6b_idx",
                    ),
                    models.Index(
                        fields=["action_type", "-created_at"],
                        name="audit_audit_action__4cc9ae_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="audit_audit_entity__9535bf_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="audit_audit_created_6e540c_idx"
                    ),
                ],
            },
        ),
    ]
