# Generated by Django 5.1.7 on 2026-01-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="user_agent",
            field=models.TextField(
                blank=True,
                help_text="Información del navegador/dispositivo del usuario",
                null=True,
                verbose_name="User Agent",
            ),
        ),
    ]
