# Generated by Django 5.1.7 on 2026-01-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_alter_auditlog_user_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="entity_id",
            field=models.CharField(
                help_text="ID de la entidad afectada",
                max_length=100,
                verbose_name="ID de la entidad",
            ),
        ),
    ]
