# Generated by Django 5.1.7 on 2026-01-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmissionRights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monto mínimo del rango",
                        max_digits=15,
                        verbose_name="Monto mínimo",
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monto máximo del rango",
                        max_digits=15,
                        verbose_name="Monto máximo",
                    ),
                ),
                (
                    "emission_right",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor del derecho de emisión para este rango",
                        max_digits=15,
                        verbose_name="Derecho de emisión",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Derecho de Emisión",
                "verbose_name_plural": "Derechos de Emisión",
                "ordering": ["min_amount"],
            },
        ),
        migrations.CreateModel(
            name="InsuranceCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "ruc",
                    models.CharField(
                        help_text="Registro Único de Contribuyentes",
                        max_length=13,
                        unique=True,
                        verbose_name="RUC",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Dirección")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Persona de contacto"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Compañía de Seguros",
                "verbose_name_plural": "Compañías de Seguros",
                "ordering": ["name"],
            },
        ),
    ]
