# Generated by Django 5.1.7 on 2026-01-04 18:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("policies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyRetention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "applies_to_premium",
                    models.BooleanField(
                        default=True,
                        help_text="Si la retención se aplica sobre la prima",
                        verbose_name="Aplica a prima",
                    ),
                ),
                (
                    "applies_to_total",
                    models.BooleanField(
                        default=False,
                        help_text="Si la retención se aplica sobre el total de la factura",
                        verbose_name="Aplica a total",
                    ),
                ),
                (
                    "custom_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Si es diferente al porcentaje estándar (opcional)",
                        max_digits=5,
                        null=True,
                        verbose_name="Porcentaje personalizado",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
            ],
            options={
                "verbose_name": "Retención de Póliza",
                "verbose_name_plural": "Retenciones de Póliza",
            },
        ),
        migrations.CreateModel(
            name="RetentionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                (
                    "retention_type",
                    models.CharField(
                        choices=[
                            ("iva", "IVA"),
                            ("islr", "Impuesto sobre la Renta"),
                            ("fonacide", "FONACIDE"),
                            ("other", "Otro"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Tipo de retención",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Porcentaje de retención (ej: 12.00 para 12%)",
                        max_digits=5,
                        verbose_name="Porcentaje",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
            ],
            options={
                "verbose_name": "Tipo de Retención",
                "verbose_name_plural": "Tipos de Retención",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="emissionrights",
            options={
                "ordering": ["min_amount", "valid_from"],
                "verbose_name": "Derecho de Emisión",
                "verbose_name_plural": "Derechos de Emisión",
            },
        ),
        migrations.AddField(
            model_name="emissionrights",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="emission_rights_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="emissionrights",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Si está activo para cálculos",
                verbose_name="Activo",
            ),
        ),
        migrations.AddField(
            model_name="emissionrights",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
        ),
        migrations.AddField(
            model_name="emissionrights",
            name="valid_from",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Fecha desde la cual aplica esta configuración",
                verbose_name="Válido desde",
            ),
        ),
        migrations.AddField(
            model_name="emissionrights",
            name="valid_until",
            field=models.DateField(
                blank=True,
                help_text="Fecha hasta la cual aplica (opcional)",
                null=True,
                verbose_name="Válido hasta",
            ),
        ),
        migrations.AlterField(
            model_name="emissionrights",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
        ),
        migrations.AlterField(
            model_name="emissionrights",
            name="emission_right",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Valor del derecho de emisión para este rango",
                max_digits=10,
                verbose_name="Derecho de emisión",
            ),
        ),
        migrations.AlterField(
            model_name="emissionrights",
            name="max_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Monto máximo del rango (incluyente)",
                max_digits=12,
                verbose_name="Monto máximo",
            ),
        ),
        migrations.AlterField(
            model_name="emissionrights",
            name="min_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Monto mínimo del rango (incluyente)",
                max_digits=12,
                verbose_name="Monto mínimo",
            ),
        ),
        migrations.AddConstraint(
            model_name="emissionrights",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_amount__gt", models.F("min_amount"))),
                name="emission_rights_min_less_than_max",
            ),
        ),
        migrations.AddConstraint(
            model_name="emissionrights",
            constraint=models.CheckConstraint(
                condition=models.Q(("emission_right__gte", 0)),
                name="emission_rights_positive",
            ),
        ),
        migrations.AddField(
            model_name="policyretention",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="policyretention",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retentions",
                to="policies.policy",
                verbose_name="Póliza",
            ),
        ),
        migrations.AddField(
            model_name="policyretention",
            name="retention_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="companies.retentiontype",
                verbose_name="Tipo de retención",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="policyretention",
            unique_together={("policy", "retention_type")},
        ),
    ]
