# Generated by Django 5.1.7 on 2026-01-04 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("policy_expiring", "Póliza por vencer"),
                            ("payment_due", "Pago pendiente"),
                            ("claim_update", "Actualización de siniestro"),
                            ("document_required", "Documento requerido"),
                            ("alert", "Alerta general"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de notificación",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("message", models.TextField(verbose_name="Mensaje")),
                ("link", models.URLField(blank=True, verbose_name="Enlace")),
                ("is_read", models.BooleanField(default=False, verbose_name="¿Leída?")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("normal", "Normal"),
                            ("high", "Alta"),
                            ("urgent", "Urgente"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="notificatio_user_id_05b4bc_idx",
                    ),
                    models.Index(
                        fields=["is_read", "priority"],
                        name="notificatio_is_read_584b29_idx",
                    ),
                ],
            },
        ),
    ]
