# Generated by Django 5.1.7 on 2026-01-04 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0001_initial"),
        ("invoices", "0001_initial"),
        ("notifications", "0001_initial"),
        ("policies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("claim_reported", "Siniestro Reportado"),
                            ("claim_updated", "Siniestro Actualizado"),
                            ("claim_liquidated", "Siniestro Liquidado"),
                            ("claim_paid", "Siniestro Pagado"),
                            ("claim_rejected", "Siniestro Rechazado"),
                            ("policy_expiring", "Póliza por Vencer"),
                            ("payment_due", "Pago Pendiente"),
                            ("payment_overdue", "Pago Vencido"),
                            ("invoice_generated", "Factura Generada"),
                            ("settlement_signed", "Finiquito Firmado"),
                            ("broker_notification", "Notificación a Broker"),
                            ("insurer_notification", "Notificación a Aseguradora"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Plantilla",
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("user", "Usuario del Sistema"),
                            ("broker", "Broker"),
                            ("insurer", "Aseguradora"),
                            ("client", "Cliente"),
                            ("financial", "Gerencia Financiera"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Destinatario",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Asunto del email - puede incluir variables ej: {{claim_number}}",
                        max_length=255,
                        verbose_name="Asunto",
                    ),
                ),
                (
                    "body_html",
                    models.TextField(
                        help_text="Cuerpo del email en HTML - puede incluir variables",
                        verbose_name="Cuerpo HTML",
                    ),
                ),
                (
                    "body_text",
                    models.TextField(
                        blank=True,
                        help_text="Versión texto plano (opcional)",
                        verbose_name="Cuerpo Texto Plano",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de Email",
                "verbose_name_plural": "Plantillas de Email",
                "ordering": ["template_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        max_length=254, verbose_name="Email del Destinatario"
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Nombre del Destinatario",
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Asunto")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Enviado"),
                            ("failed", "Fallido"),
                            ("pending", "Pendiente"),
                            ("simulated", "Simulado"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Enviado"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensaje de Error"),
                ),
                (
                    "context_data",
                    models.JSONField(
                        default=dict,
                        help_text="Variables utilizadas en la plantilla",
                        verbose_name="Datos del Contexto",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="claims.claim",
                        verbose_name="Siniestro Relacionado",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="invoices.invoice",
                        verbose_name="Factura Relacionada",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="policies.policy",
                        verbose_name="Póliza Relacionada",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="notifications.emailtemplate",
                        verbose_name="Plantilla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Email",
                "verbose_name_plural": "Logs de Email",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="notificatio_status_6192b4_idx",
                    ),
                    models.Index(
                        fields=["recipient_email"],
                        name="notificatio_recipie_25af1a_idx",
                    ),
                ],
            },
        ),
    ]
