# Generated by Django 5.1.7 on 2026-01-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("claim_reported", "Siniestro Reportado"),
                    ("claim_updated", "Siniestro Actualizado"),
                    ("claim_liquidated", "Siniestro Liquidado"),
                    ("claim_paid", "Siniestro Pagado"),
                    ("claim_rejected", "Siniestro Rechazado"),
                    ("policy_expiring", "Póliza por Vencer"),
                    ("policy_expired", "Póliza Vencida"),
                    ("payment_due", "Pago Pendiente"),
                    ("payment_overdue", "Pago Vencido"),
                    ("payment_completed", "Pago Completado"),
                    ("invoice_generated", "Factura Generada"),
                    ("invoice_overdue", "Factura Vencida"),
                    ("claim_overdue", "Siniestro Atrasado"),
                    ("document_overdue", "Documento Vencido"),
                    ("maintenance_required", "Mantenimiento Requerido"),
                    ("settlement_signed", "Finiquito Firmado"),
                    ("system_alert", "Alerta del Sistema"),
                    ("broker_notification", "Notificación a Broker"),
                    ("insurer_notification", "Notificación a Aseguradora"),
                ],
                max_length=30,
                verbose_name="Tipo de Plantilla",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("policy_expiring", "Póliza por vencer"),
                    ("policy_expired", "Póliza vencida"),
                    ("payment_due", "Pago pendiente"),
                    ("invoice_overdue", "Factura vencida"),
                    ("claim_update", "Actualización de siniestro"),
                    ("claim_overdue", "Siniestro atrasado"),
                    ("document_required", "Documento requerido"),
                    ("document_overdue", "Documento vencido"),
                    ("maintenance_required", "Mantenimiento requerido"),
                    ("system_alert", "Alerta del sistema"),
                    ("alert", "Alerta general"),
                ],
                max_length=20,
                verbose_name="Tipo de notificación",
            ),
        ),
    ]
