# Generated by Django 5.1.7 on 2026-01-04 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_emailtemplate_emaillog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre de la alerta"
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("policy_expiring", "Póliza por vencer"),
                            ("policy_expired", "Póliza vencida"),
                            ("invoice_overdue", "Factura vencida"),
                            ("claim_overdue", "Siniestro atrasado"),
                            ("document_overdue", "Documento vencido"),
                            ("payment_due", "Pago próximo"),
                            ("maintenance_required", "Mantenimiento requerido"),
                            ("system_alert", "Alerta del sistema"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de alerta",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=dict,
                        help_text="Condiciones JSON para activar la alerta",
                        verbose_name="Condiciones",
                    ),
                ),
                (
                    "email_recipients",
                    models.TextField(
                        blank=True,
                        help_text="Emails separados por comas",
                        verbose_name="Emails adicionales",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Diario"),
                            ("weekly", "Semanal"),
                            ("monthly", "Mensual"),
                            ("realtime", "Tiempo real"),
                        ],
                        default="daily",
                        max_length=10,
                        verbose_name="Frecuencia",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última ejecución"
                    ),
                ),
                (
                    "next_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Próxima ejecución"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        blank=True,
                        related_name="alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinatarios",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta",
                "verbose_name_plural": "Alertas",
                "ordering": ["-created_at"],
            },
        ),
    ]
